Title =  "Changkun's Blog"
LanguageCode = "en-US"
BaseUrl = "https://blog.changkun.de/"
Theme =  "changkun"
MetaDataFormat =  "yaml"
CanonifyUrls =  true
BuildDrafts =  false
PaginatePath =  "p"
Paginate = 5
DisablePathToLower =  false
HasCJKLanguage = true
pygmentsUseClasses=true
UglyUrls = false
disqusShortname = "changkun"
[permalinks]
  posts = "/:slug"
[markup.highlight]
  anchorLineNos = false
  codeFences = true
  guessSyntax = true
  hl_Lines = ""
  lineAnchors = ""
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  noClasses = true
  style = "vs"
  tabWidth = 4
[markup.goldmark.renderer]
    unsafe= true

[Params]
  Introduce = "Stop Talking. Just Coding."
  Description = "Science | Art | Blog"
  Keywords =  "Changkun Ou,Blog,Science,Art,Tech,Life,Notes,Reading,Think,Share"
  Subtitle = "Science and art, life in between."
  Imglogo = "/images/logo.png"
  AuthorImg = "/images/logo.png"
  DateFormat = "2006-01-02"
  YearFormat = "2006 年"
  MonthFormat = "01-02"
  GoogleAnalytics = "UA-80889616-2"
  Fancybox = false

[Author]
  Name = "Changkun Ou"

[[Menu.Main]]
  Name = "Home"
  Pre = "home"
  URL = "/"
  Weight = 1
[[Menu.Main]]
  Name = "Archives"
  Pre = "archive"
  URL = "/posts/"
  Weight = 2
[[Menu.Main]]
  Name = "Tags"
  Pre = "tag"
  URL = "/tags/"
  Weight = 3
[[Menu.Main]]
  Name = "Bio"
  Pre = "user"
  URL = "/about/"
  Weight = 4

[[Params.Socials]]
  Name = "Homepage"
  Icon = "home"
  URL = "https://changkun.de"

[[Params.Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://changkun.de/s/github"

[[Params.Socials]]
  Name = "Email"
  Icon = "envelope"
  URL = "https://changkun.de/s/email"

[[Params.Socials]]
  Name = "YouTube"
  Icon = "youtube"
  URL = "https://changkun.de/s/youtube"
[[Params.Socials]]
  Name = "Twitter"
  Icon = "twitter"
  URL = "https://changkun.de/s/twitter"

[[Params.Socials]]
  Name = "Zhihu"
  Icon = "book"
  URL = "https://changkun.de/s/zhihu"

[[Params.Links]]
  Name = "Frimin"
  Icon = "users"
  URL = "https://www.frimin.com/"
[[Params.Links]]
  Name = "ZZZero"
  Icon = "user-secret"
  URL = "https://www.zz-zero.com/"
[[Params.Links]]
  Name = "march1993"
  Icon = "user-md"
  URL = "https://march1993.com/en/"
[[Params.Links]]
  Name = "Qcrao"
  Icon = "tree"
  URL = "https://qcrao.com"