Title =  "Changkun's Blog"
LanguageCode = "en-US"
BaseUrl = "https://blogchangkun.de/"
Theme =  "changkun"
MetaDataFormat =  "yaml"
CanonifyUrls =  true
BuildDrafts =  false
PaginatePath =  "p"
Paginate = 8
DisablePathToLower =  false
HasCJKLanguage = true
UglyUrls = false
PygmentsStyle = "monokai"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true

[Params]
  Introduce = "Think Difficulty"
  Description = "Science | Art | Blog"
  Keywords =  "Changkun Ou,Blog,Science,Art,Tech,Life,Notes,Reading,Think,Share"
  Subtitle = "Science and art, life in between."
  Imglogo = "/images/logo.png"
  AuthorImg = "/images/logo.png"
  DateFormat = "2006-01-02"
  YearFormat = "2006 年"
  MonthFormat = "01-02"
  GoogleAnalytics = "UA-80889616-2"
  Fancybox = false

[Author]
  Name = "Changkun Ou"

[[Menu.Main]]
  Name = "Home"
  Pre = "home"
  URL = "/"
  Weight = 1
[[Menu.Main]]
  Name = "Archives"
  Pre = "archive"
  URL = "/archives/"
  Weight = 2
[[Menu.Main]]
  Name = "Tags"
  Pre = "tag"
  URL = "/tags/"
  Weight = 3
[[Menu.Main]]
  Name = "About"
  Pre = "user"
  URL = "/about/"
  Weight = 4

[[Params.Socials]]
  Name = "Homepage"
  Icon = "home"
  URL = "https://changkun.de"

[[Params.Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/changkun"

[[Params.Socials]]
  Name = "Email"
  Icon = "envelope"
  URL = "mailto:hi[_at_]changkun.de"

[[Params.Socials]]
  Name = "YouTube"
  Icon = "youtube"
  URL = "https://www.youtube.com/channel/UCtujb7c9eudbVEkAsIRZR3w"
[[Params.Socials]]
  Name = "Twitter"
  Icon = "twitter"
  URL = "https://twitter.com/ouchangkun"

[[Params.Socials]]
  Name = "Zhihu"
  Icon = "book"
  URL = "https://www.zhihu.com/people/ouchangkun"
