# Copyright (c) 2020 Changkun Ou. All rights reserved.

Title =  "Changkun's Blog"
LanguageCode = "en-US"
BaseUrl = "https://changkun.de/blog"
Theme =  "changkun"
MetaDataFormat =  "yaml"
CanonifyUrls =  true
BuildDrafts =  false
enableGitInfo = true
[pagination]
  pagerSize = 5
  path = "p"
DisablePathToLower =  false
HasCJKLanguage = true
pygmentsUseClasses=true
UglyUrls = false
[permalinks]
  posts = "/:slug"
  ideas = "/ideas/:slug"
[markup.highlight]
  anchorLineNos = false
  codeFences = true
  guessSyntax = true
  hl_Lines = ""
  lineAnchors = ""
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  noClasses = false
  style = "vs"
  tabWidth = 4

# For chinese characters (not important for me):
# [markup]
#   defaultMarkdownHandler = "blackfriday"
# [markup.blackfriday]
#   extensions = ["joinLines"]

[markup.goldmark.renderer]
    unsafe= true

[Params]
  Introduce = "Human-AI interaction researcher, engineer, and writer."
  Description = "Bridging HCI, AI, and systems programming. Building intelligent human-in-the-loop optimization systems. Informed by psychology, sociology, cognitive science, and philosophy."
  Keywords =  "Changkun Ou,Blog,Science,Art,Tech,Life,Notes,Reading,Think,Share"
  Subtitle = "Science and art, life in between."
  Imglogo = "https://changkun.de/logo.png"
  AuthorImg = "https://changkun.de/logo.png"
  DateFormat = "2006-01-02"
  YearFormat = "2006 年"
  MonthFormat = "01-02"
  GoogleAnalytics = "UA-80889616-2"
  Fancybox = false

[Params.Author]
  Name = "Changkun Ou"

[[Menu.Main]]
  Name = "Home"
  Pre = "home"
  URL = "/"
  Weight = 1
[[Menu.Main]]
  Name = "Ideas"
  Pre = "lightbulb-o"
  URL = "/ideas/"
  Weight = 2
[[Menu.Main]]
  Name = "Posts"
  Pre = "archive"
  URL = "/posts/"
  Weight = 3
[[Menu.Main]]
  Name = "Tags"
  Pre = "tag"
  URL = "/tags/"
  Weight = 4
[[Menu.Main]]
  Name = "Bio"
  Pre = "user"
  URL = "/about/"
  Weight = 5

[[Params.Socials]]
  Name = "Homepage"
  Icon = "home"
  URL = "https://changkun.de"
[[Params.Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/changkun"
[[Params.Socials]]
  Name = "Email"
  Icon = "envelope"
  URL = "mailto:contact@changkun.de"
[[Params.Socials]]
  Name = "Institution"
  Icon = "university"
  URL = "https://www.medien.ifi.lmu.de/team/changkun.ou/"
[[Params.Socials]]
  Name = "Google Scholar"
  Icon = "graduation-cap"
  URL = "https://scholar.google.de/citations?user=3qjB-eUAAAAJ"
[[Params.Socials]]
  Name = "LinkedIn"
  Icon = "linkedin"
  URL = "https://www.linkedin.com/in/changkun/"
[[Params.Socials]]
  Name = "Twitter"
  Icon = "twitter"
  URL = "https://twitter.com/ouchangkun"
[[Params.Socials]]
  Name = "Instagram"
  Icon = "instagram"
  URL = "https://www.instagram.com/ouchangkun"
[[Params.Socials]]
  Name = "YouTube"
  Icon = "youtube"
  URL = "https://www.youtube.com/channel/UCtujb7c9eudbVEkAsIRZR3w"
[[Params.Socials]]
  Name = "Stack Overflow"
  Icon = "stack-overflow"
  URL = "https://stackoverflow.com/users/3819460/changkun"
[[Params.Socials]]
  Name = "Zhihu"
  Icon = "book"
  URL = "https://www.zhihu.com/people/ouchangkun"
[[Params.Socials]]
  Name = "Facebook"
  Icon = "facebook"
  URL = "https://www.facebook.com/ouchangkun"
[[Params.Socials]]
  Name = "Telegram"
  Icon = "telegram"
  URL = "https://t.me/ouchangkun"

[[Params.Links]]
  Name = "march1993"
  Icon = "user-md"
  URL = "https://march1993.com/en/"
[[Params.Links]]
  Name = "qcrao"
  Icon = "tree"
  URL = "https://qcrao.com"
[[Params.Links]]
  Name = "maiyang"
  Icon = "coffee"
  URL = "https://maiyang.me"
[[Params.Links]]
  Name = "Xargin"
  Icon = "tasks"
  URL = "https://xargin.com/"
[[Params.Links]]
  Name = "Muniao"
  Icon = "tree"
  URL = "https://www.qtmuniao.com/"
# https://fontawesome.com/v4.7.0/icons/