# Copyright 2020 Changkun Ou. All rights reserved.

version: '3'

services:
  blog:
    build: .
    restart: always
    image: blog:latest
    deploy:
      replicas: 3
    environment:
      - "BLOG_ADDR=blog:80"
    networks:
      - traefik_proxy
networks:
  traefik_proxy:
    external: true