name: blog
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
      id: go
    - name: setup hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.60.1'
        extended: true
    - uses: actions/checkout@v2
    - name: build
      env:
        USER: ${{ secrets.SERVER_USER }}
        KEY: ${{ secrets.SERVER_KEY }}
        DOMAIN: ${{ secrets.SERVER_DOMAIN }}
        PATH: ${{ secrets.SERVER_PATH }}
      run: /usr/bin/make
        # mkdir ~/.ssh
        # echo "$KEY" | tr -d '\r' > ~/.ssh/idkey
        # chmod 400 ~/.ssh/idkey
        # eval "$(ssh-agent -s)"
        # ssh-add ~/.ssh/idkey
        # ssh-keyscan -H $DOMAIN >> ~/.ssh/known_hosts
        # rsync -va public $USER@$DOMAIN:$PATH
